// <auto-generated />
using System;
using DragonForge.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DragonForge.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260410122948_AddIdentityAndGameEntities")]
    partial class AddIdentityAndGameEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DragonForge.Api.Models.Entities.ChildOtp", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChildProfileId")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Used")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("ChildProfileId");

                    b.HasIndex("Code");

                    b.ToTable("ChildOtps");
                });

            modelBuilder.Entity("DragonForge.Api.Models.Entities.ChildProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarChoice")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrentStage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("HighestLevelCompleted")
                        .HasColumnType("integer");

                    b.Property<Guid>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<int>("TotalPoints")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("ChildProfiles");
                });

            modelBuilder.Entity("DragonForge.Api.Models.Entities.DeviceSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChildProfileId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeviceName")
                        .HasColumnType("text");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ChildProfileId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.ToTable("DeviceSessions");
                });

            modelBuilder.Entity("DragonForge.Api.Models.Entities.LevelAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Accuracy")
                        .HasPrecision(5, 1)
                        .HasColumnType("numeric(5,1)");

                    b.Property<Guid>("ChildProfileId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("HeartsRemaining")
                        .HasColumnType("integer");

                    b.Property<int>("LevelDefinitionId")
                        .HasColumnType("integer");

                    b.Property<bool>("Passed")
                        .HasColumnType("boolean");

                    b.Property<int>("PointsAwarded")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Wpm")
                        .HasPrecision(6, 1)
                        .HasColumnType("numeric(6,1)");

                    b.HasKey("Id");

                    b.HasIndex("ChildProfileId");

                    b.HasIndex("LevelDefinitionId");

                    b.ToTable("LevelAttempts");
                });

            modelBuilder.Entity("DragonForge.Api.Models.Entities.LevelDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BasePoints")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("LevelNumber")
                        .HasColumnType("integer");

                    b.Property<int?>("MinWpmForBonus")
                        .HasColumnType("integer");

                    b.Property<string>("Phase")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PromptTexts")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LevelNumber")
                        .IsUnique();

                    b.ToTable("LevelDefinitions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BasePoints = 10,
                            Description = "Practice the left home row keys: a s d f",
                            LevelNumber = 1,
                            Phase = "Egg",
                            PromptTexts = "[\"ff dd ss aa fd sa df as\",\"sad fad dad add ads aff\",\"as sad dad fad dads adds\",\"fads dass sadf fdsa asdf\"]",
                            Title = "Home Row Left Hand"
                        },
                        new
                        {
                            Id = 2,
                            BasePoints = 10,
                            Description = "Practice the right home row keys: j k l ;",
                            LevelNumber = 2,
                            Phase = "Egg",
                            PromptTexts = "[\"jj kk ll ;; jk lk jl kj\",\"jkl lkj kjl ljk ;lk j;l\",\"jk kl l; ;l lk kj j; ;j\",\"jkl; ;lkj kj;l l;kj jkl;\"]",
                            Title = "Home Row Right Hand"
                        },
                        new
                        {
                            Id = 3,
                            BasePoints = 10,
                            Description = "Combine left and right home row: a s d f j k l ;",
                            LevelNumber = 3,
                            Phase = "Egg",
                            PromptTexts = "[\"ask all fall lads flask salad\",\"dad jak lad ask sad fall\",\"falls asks salads flasks lads\",\"a sad lad asks dad for salad\"]",
                            Title = "Home Row Full"
                        },
                        new
                        {
                            Id = 4,
                            BasePoints = 10,
                            Description = "All home row keys including g and h",
                            LevelNumber = 4,
                            Phase = "Egg",
                            PromptTexts = "[\"gash hash glad flag shag half\",\"flash flags gash halls shall glass\",\"had has gal lag hag jag sag dag\",\"a glad gal shall dash half a flag\"]",
                            Title = "Home Row Complete"
                        },
                        new
                        {
                            Id = 5,
                            BasePoints = 10,
                            Description = "Learn the top row left hand: q w e r t",
                            LevelNumber = 5,
                            Phase = "Egg",
                            PromptTexts = "[\"we wet rew tree were quest\",\"tree wet rew west were qwert\",\"we were free tree wet quest\",\"the tree grew wet where we rest\"]",
                            Title = "Top Row Left"
                        },
                        new
                        {
                            Id = 6,
                            BasePoints = 10,
                            Description = "Learn the top row right hand: y u i o p",
                            LevelNumber = 6,
                            Phase = "Egg",
                            PromptTexts = "[\"you your yip poi you yup\",\"pop pip you your yup poi\",\"you pour your iou yip poi\",\"you pour up yup pop poiopy\"]",
                            Title = "Top Row Right"
                        },
                        new
                        {
                            Id = 7,
                            BasePoints = 10,
                            Description = "Full top row: q w e r t y u i o p",
                            LevelNumber = 7,
                            Phase = "Egg",
                            PromptTexts = "[\"typewriter your power quite wire poetry\",\"write your quote type power rope\",\"quiet poetry typewriter proper routine\",\"you write poetry with power quite proper\"]",
                            Title = "Top Row Full"
                        },
                        new
                        {
                            Id = 8,
                            BasePoints = 15,
                            Description = "Mix home row and top row keys together",
                            LevelNumber = 8,
                            Phase = "Egg",
                            PromptTexts = "[\"the quick red fish just helped sort\",\"quest for gold right where they left\",\"quite right she sold the purple silk\",\"after the quiet hike up the top ridge\"]",
                            Title = "Home + Top Mixed"
                        },
                        new
                        {
                            Id = 9,
                            BasePoints = 10,
                            Description = "Learn the bottom row left hand: z x c v b",
                            LevelNumber = 9,
                            Phase = "Egg",
                            PromptTexts = "[\"box cab vex czar vc bx zap\",\"excavate brace cave vex box cab\",\"brave cave cab box vex czar\",\"the brave cub excavated a cave by a box\"]",
                            Title = "Bottom Row Left"
                        },
                        new
                        {
                            Id = 10,
                            BasePoints = 10,
                            Description = "Learn the bottom row right hand: n m , . /",
                            LevelNumber = 10,
                            Phase = "Egg",
                            PromptTexts = "[\"man men mine moon nom\",\"moon name mine noon moan man\",\"the man ran nine more moon men\",\"no man can name the moon in a mine\"]",
                            Title = "Bottom Row Right"
                        },
                        new
                        {
                            Id = 11,
                            BasePoints = 10,
                            Description = "Full bottom row: z x c v b n m , . /",
                            LevelNumber = 11,
                            Phase = "Egg",
                            PromptTexts = "[\"machine verb combine zone mix ban\",\"the brave zombie came back from camp\",\"a boxing van drove next to the cabin\",\"combine zinc and mix the vitamin batch\"]",
                            Title = "Bottom Row Full"
                        },
                        new
                        {
                            Id = 12,
                            BasePoints = 15,
                            Description = "Random letters from all three rows",
                            LevelNumber = 12,
                            Phase = "Egg",
                            PromptTexts = "[\"the quick brown fox jumps over a lazy dog\",\"pack my box with five dozen liquor jugs\",\"crazy viking joked with bad flux tempo\",\"how quickly jumping zebras vex fond dogs\"]",
                            Title = "All Rows Mixed"
                        },
                        new
                        {
                            Id = 13,
                            BasePoints = 15,
                            Description = "Introducing the shift key for capital letters",
                            LevelNumber = 13,
                            Phase = "Egg",
                            PromptTexts = "[\"The dog sat down and ate his food.\",\"Jack went up the hill to get water.\",\"Sam ran fast but Zoe was even faster.\",\"My friend Alex lives near the big park.\"]",
                            Title = "Capital Letters"
                        },
                        new
                        {
                            Id = 14,
                            BasePoints = 15,
                            Description = "Practice the number keys: 1 2 3 4 5 6 7 8 9 0",
                            LevelNumber = 14,
                            Phase = "Egg",
                            PromptTexts = "[\"12345 67890 13579 24680\",\"I have 3 cats and 2 dogs at home.\",\"Room 42 has 7 desks and 10 chairs.\",\"She scored 95 out of 100 on test 4.\"]",
                            Title = "Numbers Row"
                        },
                        new
                        {
                            Id = 15,
                            BasePoints = 15,
                            Description = "Practice common punctuation in real sentences",
                            LevelNumber = 15,
                            Phase = "Egg",
                            PromptTexts = "[\"Hello, how are you? I\\u0027m doing fine!\",\"Wait, what? No way! That\\u0027s so cool.\",\"She said, \\u0022Let\\u0027s go to the park today.\\u0022\",\"Can you help me? Yes, I\\u0027d love to!\"]",
                            Title = "Common Punctuation"
                        },
                        new
                        {
                            Id = 16,
                            BasePoints = 25,
                            Description = "Short and sweet two-letter words",
                            LevelNumber = 16,
                            Phase = "Hatchling",
                            PromptTexts = "[\"to is an it on at in or we do\",\"he me be us no so up if my am\",\"go by of as ox is to an it we\",\"do me no he up at in on so am\"]",
                            Title = "Two-Letter Words"
                        },
                        new
                        {
                            Id = 17,
                            BasePoints = 25,
                            Description = "Common three-letter words",
                            LevelNumber = 17,
                            Phase = "Hatchling",
                            PromptTexts = "[\"the and for cat dog run big hat\",\"red hot cup map set fox bat sun\",\"top hit fun bed log pen web van\",\"sit mix hop dig rub cut zip yam\"]",
                            Title = "Three-Letter Words"
                        },
                        new
                        {
                            Id = 18,
                            BasePoints = 35,
                            Description = "Building up to four-letter words",
                            LevelNumber = 18,
                            Phase = "Hatchling",
                            PromptTexts = "[\"jump fire bold lake home star book\",\"game fish land dark moon tree bird\",\"rain snow wind hill path road rock\",\"king gold cave song bell drum flag\"]",
                            Title = "Four-Letter Words"
                        },
                        new
                        {
                            Id = 19,
                            BasePoints = 35,
                            Description = "Longer words that build fluency",
                            LevelNumber = 19,
                            Phase = "Hatchling",
                            PromptTexts = "[\"brave flame sword quest storm light\",\"magic river tower stone water dream\",\"power cloud shine scale guard heart\",\"blaze torch forge ember lucky world\"]",
                            Title = "Five-Letter Words"
                        },
                        new
                        {
                            Id = 20,
                            BasePoints = 25,
                            Description = "A mix of two to four-letter words",
                            LevelNumber = 20,
                            Phase = "Hatchling",
                            PromptTexts = "[\"the big red fox ran to his den\",\"a cat sat on top of my old hat\",\"go fly up and see the hot sun\",\"one day she won a new pet dog\"]",
                            Title = "Mixed Short Words"
                        },
                        new
                        {
                            Id = 21,
                            BasePoints = 35,
                            Description = "A mix of four to six-letter words",
                            LevelNumber = 21,
                            Phase = "Hatchling",
                            PromptTexts = "[\"dragon flame castle knight bridge tower\",\"forest meadow stream garden shield armor\",\"battle wizard scroll potion bottle hammer\",\"dungeon portal secret hidden golden silver\"]",
                            Title = "Mixed Medium Words"
                        },
                        new
                        {
                            Id = 22,
                            BasePoints = 25,
                            Description = "Words you see all the time in reading",
                            LevelNumber = 22,
                            Phase = "Hatchling",
                            PromptTexts = "[\"about their would could people other\",\"should every after where before little\",\"because again different another through right\",\"between never under still always found\"]",
                            Title = "Common Sight Words"
                        },
                        new
                        {
                            Id = 23,
                            BasePoints = 25,
                            Description = "Simple two-word pairs to build flow",
                            LevelNumber = 23,
                            Phase = "Hatchling",
                            PromptTexts = "[\"big cat red dog old map hot sun\",\"my home one day new game go fast\",\"blue sky dark cave long road top hill\",\"fire ball ice cold gold ring red star\"]",
                            Title = "Two-Word Combos"
                        },
                        new
                        {
                            Id = 24,
                            BasePoints = 25,
                            Description = "Short phrases to build rhythm",
                            LevelNumber = 24,
                            Phase = "Hatchling",
                            PromptTexts = "[\"run very fast eat some food find the gold\",\"see the moon pet the cat fly a kite\",\"ride the wave read a book make some art\",\"find the key open the door start the fire\"]",
                            Title = "Three-Word Phrases"
                        },
                        new
                        {
                            Id = 25,
                            BasePoints = 35,
                            Description = "Slightly longer phrases for building speed",
                            LevelNumber = 25,
                            Phase = "Hatchling",
                            PromptTexts = "[\"the dragon flew high over the dark forest\",\"a brave knight stood ready for the fight\",\"the egg began to glow with warm light\",\"a tiny flame burned inside the old cave\"]",
                            Title = "Four-Word Phrases"
                        },
                        new
                        {
                            Id = 26,
                            BasePoints = 50,
                            Description = "Simple sentences without punctuation",
                            LevelNumber = 26,
                            Phase = "Hatchling",
                            PromptTexts = "[\"the small dragon ran across the green field\",\"a warm wind blew through the open window\",\"the old wizard found a glowing blue stone\",\"five birds flew over the tall castle wall\"]",
                            Title = "Short Sentences"
                        },
                        new
                        {
                            Id = 27,
                            BasePoints = 50,
                            Description = "Short sentences with proper capitalization",
                            LevelNumber = 27,
                            Phase = "Hatchling",
                            PromptTexts = "[\"The little dragon ate three fish for lunch.\",\"Anna found a shiny coin under the bridge.\",\"My best friend Max has a pet lizard.\",\"Every morning the sun rises over the hill.\"]",
                            Title = "Sentences with Capitals"
                        },
                        new
                        {
                            Id = 28,
                            BasePoints = 50,
                            Description = "Sentences ending with periods",
                            LevelNumber = 28,
                            Phase = "Hatchling",
                            PromptTexts = "[\"The cave was dark. A torch lit the way.\",\"Rain fell all day. The river rose fast.\",\"The knight drew his sword. He was ready.\",\"Stars filled the sky. The moon was full.\"]",
                            Title = "Sentences with Periods"
                        },
                        new
                        {
                            Id = 29,
                            BasePoints = 50,
                            Description = "Sentences with commas, periods, and questions",
                            LevelNumber = 29,
                            Phase = "Hatchling",
                            PromptTexts = "[\"The dragon roared, and the ground shook hard.\",\"Where did the wizard go? Nobody knows for sure.\",\"Run, jump, and fly! The race has begun.\",\"After the rain stopped, a rainbow filled the sky.\"]",
                            Title = "Mixed Punctuation"
                        },
                        new
                        {
                            Id = 30,
                            BasePoints = 75,
                            Description = "Longer sentences to test your speed",
                            LevelNumber = 30,
                            Phase = "Hatchling",
                            PromptTexts = "[\"The brave dragon flew over the mountains and landed near a quiet lake.\",\"A young wizard opened an old book and found a map to hidden treasure.\",\"The knight rode through the forest until he reached the stone castle.\",\"Every night the stars told stories about the dragons of long ago.\"]",
                            Title = "Medium Sentences"
                        });
                });

            modelBuilder.Entity("DragonForge.Api.Models.Entities.Parent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("DragonForge.Api.Models.Entities.ChildOtp", b =>
                {
                    b.HasOne("DragonForge.Api.Models.Entities.ChildProfile", "ChildProfile")
                        .WithMany()
                        .HasForeignKey("ChildProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChildProfile");
                });

            modelBuilder.Entity("DragonForge.Api.Models.Entities.ChildProfile", b =>
                {
                    b.HasOne("DragonForge.Api.Models.Entities.Parent", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("DragonForge.Api.Models.Entities.DeviceSession", b =>
                {
                    b.HasOne("DragonForge.Api.Models.Entities.ChildProfile", "ChildProfile")
                        .WithMany("DeviceSessions")
                        .HasForeignKey("ChildProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChildProfile");
                });

            modelBuilder.Entity("DragonForge.Api.Models.Entities.LevelAttempt", b =>
                {
                    b.HasOne("DragonForge.Api.Models.Entities.ChildProfile", "ChildProfile")
                        .WithMany("Attempts")
                        .HasForeignKey("ChildProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DragonForge.Api.Models.Entities.LevelDefinition", "LevelDefinition")
                        .WithMany()
                        .HasForeignKey("LevelDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChildProfile");

                    b.Navigation("LevelDefinition");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("DragonForge.Api.Models.Entities.Parent", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("DragonForge.Api.Models.Entities.Parent", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DragonForge.Api.Models.Entities.Parent", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("DragonForge.Api.Models.Entities.Parent", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DragonForge.Api.Models.Entities.ChildProfile", b =>
                {
                    b.Navigation("Attempts");

                    b.Navigation("DeviceSessions");
                });

            modelBuilder.Entity("DragonForge.Api.Models.Entities.Parent", b =>
                {
                    b.Navigation("Children");
                });
#pragma warning restore 612, 618
        }
    }
}
