// <auto-generated />
using System;
using DragonForge.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DragonForge.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260410192505_AddLevels31to50")]
    partial class AddLevels31to50
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DragonForge.Api.Models.Entities.ChildOtp", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChildProfileId")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Used")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("ChildProfileId");

                    b.HasIndex("Code");

                    b.ToTable("ChildOtps");
                });

            modelBuilder.Entity("DragonForge.Api.Models.Entities.ChildProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarChoice")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrentStage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("HighestLevelCompleted")
                        .HasColumnType("integer");

                    b.Property<Guid>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<int>("TotalPoints")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("ChildProfiles");
                });

            modelBuilder.Entity("DragonForge.Api.Models.Entities.DeviceSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChildProfileId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeviceName")
                        .HasColumnType("text");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ChildProfileId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.ToTable("DeviceSessions");
                });

            modelBuilder.Entity("DragonForge.Api.Models.Entities.LevelAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Accuracy")
                        .HasPrecision(5, 1)
                        .HasColumnType("numeric(5,1)");

                    b.Property<Guid>("ChildProfileId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("HeartsRemaining")
                        .HasColumnType("integer");

                    b.Property<int>("LevelDefinitionId")
                        .HasColumnType("integer");

                    b.Property<bool>("Passed")
                        .HasColumnType("boolean");

                    b.Property<int>("PointsAwarded")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Wpm")
                        .HasPrecision(6, 1)
                        .HasColumnType("numeric(6,1)");

                    b.HasKey("Id");

                    b.HasIndex("ChildProfileId");

                    b.HasIndex("LevelDefinitionId");

                    b.ToTable("LevelAttempts");
                });

            modelBuilder.Entity("DragonForge.Api.Models.Entities.LevelDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BasePoints")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("LevelNumber")
                        .HasColumnType("integer");

                    b.Property<int?>("MinWpmForBonus")
                        .HasColumnType("integer");

                    b.Property<string>("Phase")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PromptTexts")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LevelNumber")
                        .IsUnique();

                    b.ToTable("LevelDefinitions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BasePoints = 10,
                            Description = "Practice the left home row keys: a s d f",
                            LevelNumber = 1,
                            Phase = "Egg",
                            PromptTexts = "[\"ff dd ss aa fd sa df as\",\"sad fad dad add ads aff\",\"as sad dad fad dads adds\",\"fads dass sadf fdsa asdf\"]",
                            Title = "Home Row Left Hand"
                        },
                        new
                        {
                            Id = 2,
                            BasePoints = 10,
                            Description = "Practice the right home row keys: j k l ;",
                            LevelNumber = 2,
                            Phase = "Egg",
                            PromptTexts = "[\"jj kk ll ;; jk lk jl kj\",\"jkl lkj kjl ljk ;lk j;l\",\"jk kl l; ;l lk kj j; ;j\",\"jkl; ;lkj kj;l l;kj jkl;\"]",
                            Title = "Home Row Right Hand"
                        },
                        new
                        {
                            Id = 3,
                            BasePoints = 10,
                            Description = "Combine left and right home row: a s d f j k l ;",
                            LevelNumber = 3,
                            Phase = "Egg",
                            PromptTexts = "[\"ask all fall lads flask salad\",\"dad jak lad ask sad fall\",\"falls asks salads flasks lads\",\"a sad lad asks dad for salad\"]",
                            Title = "Home Row Full"
                        },
                        new
                        {
                            Id = 4,
                            BasePoints = 10,
                            Description = "All home row keys including g and h",
                            LevelNumber = 4,
                            Phase = "Egg",
                            PromptTexts = "[\"gash hash glad flag shag half\",\"flash flags gash halls shall glass\",\"had has gal lag hag jag sag dag\",\"a glad gal shall dash half a flag\"]",
                            Title = "Home Row Complete"
                        },
                        new
                        {
                            Id = 5,
                            BasePoints = 10,
                            Description = "Learn the top row left hand: q w e r t",
                            LevelNumber = 5,
                            Phase = "Egg",
                            PromptTexts = "[\"we wet rew tree were quest\",\"tree wet rew west were qwert\",\"we were free tree wet quest\",\"the tree grew wet where we rest\"]",
                            Title = "Top Row Left"
                        },
                        new
                        {
                            Id = 6,
                            BasePoints = 10,
                            Description = "Learn the top row right hand: y u i o p",
                            LevelNumber = 6,
                            Phase = "Egg",
                            PromptTexts = "[\"you your yip poi you yup\",\"pop pip you your yup poi\",\"you pour your iou yip poi\",\"you pour up yup pop poiopy\"]",
                            Title = "Top Row Right"
                        },
                        new
                        {
                            Id = 7,
                            BasePoints = 10,
                            Description = "Full top row: q w e r t y u i o p",
                            LevelNumber = 7,
                            Phase = "Egg",
                            PromptTexts = "[\"typewriter your power quite wire poetry\",\"write your quote type power rope\",\"quiet poetry typewriter proper routine\",\"you write poetry with power quite proper\"]",
                            Title = "Top Row Full"
                        },
                        new
                        {
                            Id = 8,
                            BasePoints = 15,
                            Description = "Mix home row and top row keys together",
                            LevelNumber = 8,
                            Phase = "Egg",
                            PromptTexts = "[\"the quick red fish just helped sort\",\"quest for gold right where they left\",\"quite right she sold the purple silk\",\"after the quiet hike up the top ridge\"]",
                            Title = "Home + Top Mixed"
                        },
                        new
                        {
                            Id = 9,
                            BasePoints = 10,
                            Description = "Learn the bottom row left hand: z x c v b",
                            LevelNumber = 9,
                            Phase = "Egg",
                            PromptTexts = "[\"box cab vex czar vc bx zap\",\"excavate brace cave vex box cab\",\"brave cave cab box vex czar\",\"the brave cub excavated a cave by a box\"]",
                            Title = "Bottom Row Left"
                        },
                        new
                        {
                            Id = 10,
                            BasePoints = 10,
                            Description = "Learn the bottom row right hand: n m , . /",
                            LevelNumber = 10,
                            Phase = "Egg",
                            PromptTexts = "[\"man men mine moon nom\",\"moon name mine noon moan man\",\"the man ran nine more moon men\",\"no man can name the moon in a mine\"]",
                            Title = "Bottom Row Right"
                        },
                        new
                        {
                            Id = 11,
                            BasePoints = 10,
                            Description = "Full bottom row: z x c v b n m , . /",
                            LevelNumber = 11,
                            Phase = "Egg",
                            PromptTexts = "[\"machine verb combine zone mix ban\",\"the brave zombie came back from camp\",\"a boxing van drove next to the cabin\",\"combine zinc and mix the vitamin batch\"]",
                            Title = "Bottom Row Full"
                        },
                        new
                        {
                            Id = 12,
                            BasePoints = 15,
                            Description = "Random letters from all three rows",
                            LevelNumber = 12,
                            Phase = "Egg",
                            PromptTexts = "[\"the quick brown fox jumps over a lazy dog\",\"pack my box with five dozen liquor jugs\",\"crazy viking joked with bad flux tempo\",\"how quickly jumping zebras vex fond dogs\"]",
                            Title = "All Rows Mixed"
                        },
                        new
                        {
                            Id = 13,
                            BasePoints = 15,
                            Description = "Introducing the shift key for capital letters",
                            LevelNumber = 13,
                            Phase = "Egg",
                            PromptTexts = "[\"The dog sat down and ate his food.\",\"Jack went up the hill to get water.\",\"Sam ran fast but Zoe was even faster.\",\"My friend Alex lives near the big park.\"]",
                            Title = "Capital Letters"
                        },
                        new
                        {
                            Id = 14,
                            BasePoints = 15,
                            Description = "Practice the number keys: 1 2 3 4 5 6 7 8 9 0",
                            LevelNumber = 14,
                            Phase = "Egg",
                            PromptTexts = "[\"12345 67890 13579 24680\",\"I have 3 cats and 2 dogs at home.\",\"Room 42 has 7 desks and 10 chairs.\",\"She scored 95 out of 100 on test 4.\"]",
                            Title = "Numbers Row"
                        },
                        new
                        {
                            Id = 15,
                            BasePoints = 15,
                            Description = "Practice common punctuation in real sentences",
                            LevelNumber = 15,
                            Phase = "Egg",
                            PromptTexts = "[\"Hello, how are you? I\\u0027m doing fine!\",\"Wait, what? No way! That\\u0027s so cool.\",\"She said, \\u0022Let\\u0027s go to the park today.\\u0022\",\"Can you help me? Yes, I\\u0027d love to!\"]",
                            Title = "Common Punctuation"
                        },
                        new
                        {
                            Id = 16,
                            BasePoints = 25,
                            Description = "Short and sweet two-letter words",
                            LevelNumber = 16,
                            Phase = "Hatchling",
                            PromptTexts = "[\"to is an it on at in or we do\",\"he me be us no so up if my am\",\"go by of as ox is to an it we\",\"do me no he up at in on so am\"]",
                            Title = "Two-Letter Words"
                        },
                        new
                        {
                            Id = 17,
                            BasePoints = 25,
                            Description = "Common three-letter words",
                            LevelNumber = 17,
                            Phase = "Hatchling",
                            PromptTexts = "[\"the and for cat dog run big hat\",\"red hot cup map set fox bat sun\",\"top hit fun bed log pen web van\",\"sit mix hop dig rub cut zip yam\"]",
                            Title = "Three-Letter Words"
                        },
                        new
                        {
                            Id = 18,
                            BasePoints = 35,
                            Description = "Building up to four-letter words",
                            LevelNumber = 18,
                            Phase = "Hatchling",
                            PromptTexts = "[\"jump fire bold lake home star book\",\"game fish land dark moon tree bird\",\"rain snow wind hill path road rock\",\"king gold cave song bell drum flag\"]",
                            Title = "Four-Letter Words"
                        },
                        new
                        {
                            Id = 19,
                            BasePoints = 35,
                            Description = "Longer words that build fluency",
                            LevelNumber = 19,
                            Phase = "Hatchling",
                            PromptTexts = "[\"brave flame sword quest storm light\",\"magic river tower stone water dream\",\"power cloud shine scale guard heart\",\"blaze torch forge ember lucky world\"]",
                            Title = "Five-Letter Words"
                        },
                        new
                        {
                            Id = 20,
                            BasePoints = 25,
                            Description = "A mix of two to four-letter words",
                            LevelNumber = 20,
                            Phase = "Hatchling",
                            PromptTexts = "[\"the big red fox ran to his den\",\"a cat sat on top of my old hat\",\"go fly up and see the hot sun\",\"one day she won a new pet dog\"]",
                            Title = "Mixed Short Words"
                        },
                        new
                        {
                            Id = 21,
                            BasePoints = 35,
                            Description = "A mix of four to six-letter words",
                            LevelNumber = 21,
                            Phase = "Hatchling",
                            PromptTexts = "[\"dragon flame castle knight bridge tower\",\"forest meadow stream garden shield armor\",\"battle wizard scroll potion bottle hammer\",\"dungeon portal secret hidden golden silver\"]",
                            Title = "Mixed Medium Words"
                        },
                        new
                        {
                            Id = 22,
                            BasePoints = 25,
                            Description = "Words you see all the time in reading",
                            LevelNumber = 22,
                            Phase = "Hatchling",
                            PromptTexts = "[\"about their would could people other\",\"should every after where before little\",\"because again different another through right\",\"between never under still always found\"]",
                            Title = "Common Sight Words"
                        },
                        new
                        {
                            Id = 23,
                            BasePoints = 25,
                            Description = "Simple two-word pairs to build flow",
                            LevelNumber = 23,
                            Phase = "Hatchling",
                            PromptTexts = "[\"big cat red dog old map hot sun\",\"my home one day new game go fast\",\"blue sky dark cave long road top hill\",\"fire ball ice cold gold ring red star\"]",
                            Title = "Two-Word Combos"
                        },
                        new
                        {
                            Id = 24,
                            BasePoints = 25,
                            Description = "Short phrases to build rhythm",
                            LevelNumber = 24,
                            Phase = "Hatchling",
                            PromptTexts = "[\"run very fast eat some food find the gold\",\"see the moon pet the cat fly a kite\",\"ride the wave read a book make some art\",\"find the key open the door start the fire\"]",
                            Title = "Three-Word Phrases"
                        },
                        new
                        {
                            Id = 25,
                            BasePoints = 35,
                            Description = "Slightly longer phrases for building speed",
                            LevelNumber = 25,
                            Phase = "Hatchling",
                            PromptTexts = "[\"the dragon flew high over the dark forest\",\"a brave knight stood ready for the fight\",\"the egg began to glow with warm light\",\"a tiny flame burned inside the old cave\"]",
                            Title = "Four-Word Phrases"
                        },
                        new
                        {
                            Id = 26,
                            BasePoints = 50,
                            Description = "Simple sentences without punctuation",
                            LevelNumber = 26,
                            Phase = "Hatchling",
                            PromptTexts = "[\"the small dragon ran across the green field\",\"a warm wind blew through the open window\",\"the old wizard found a glowing blue stone\",\"five birds flew over the tall castle wall\"]",
                            Title = "Short Sentences"
                        },
                        new
                        {
                            Id = 27,
                            BasePoints = 50,
                            Description = "Short sentences with proper capitalization",
                            LevelNumber = 27,
                            Phase = "Hatchling",
                            PromptTexts = "[\"The little dragon ate three fish for lunch.\",\"Anna found a shiny coin under the bridge.\",\"My best friend Max has a pet lizard.\",\"Every morning the sun rises over the hill.\"]",
                            Title = "Sentences with Capitals"
                        },
                        new
                        {
                            Id = 28,
                            BasePoints = 50,
                            Description = "Sentences ending with periods",
                            LevelNumber = 28,
                            Phase = "Hatchling",
                            PromptTexts = "[\"The cave was dark. A torch lit the way.\",\"Rain fell all day. The river rose fast.\",\"The knight drew his sword. He was ready.\",\"Stars filled the sky. The moon was full.\"]",
                            Title = "Sentences with Periods"
                        },
                        new
                        {
                            Id = 29,
                            BasePoints = 50,
                            Description = "Sentences with commas, periods, and questions",
                            LevelNumber = 29,
                            Phase = "Hatchling",
                            PromptTexts = "[\"The dragon roared, and the ground shook hard.\",\"Where did the wizard go? Nobody knows for sure.\",\"Run, jump, and fly! The race has begun.\",\"After the rain stopped, a rainbow filled the sky.\"]",
                            Title = "Mixed Punctuation"
                        },
                        new
                        {
                            Id = 30,
                            BasePoints = 75,
                            Description = "Longer sentences to test your speed",
                            LevelNumber = 30,
                            Phase = "Hatchling",
                            PromptTexts = "[\"The brave dragon flew over the mountains and landed near a quiet lake.\",\"A young wizard opened an old book and found a map to hidden treasure.\",\"The knight rode through the forest until he reached the stone castle.\",\"Every night the stars told stories about the dragons of long ago.\"]",
                            Title = "Medium Sentences"
                        },
                        new
                        {
                            Id = 31,
                            BasePoints = 75,
                            Description = "Full sentences with all keys",
                            LevelNumber = 31,
                            Phase = "Drake",
                            PromptTexts = "[\"Jimothy packed his bag and set off down the winding forest path at dawn.\",\"The little dragon tried to keep up, tripping over roots and stones.\",\"Smoke curled from the dragon\\u0027s nose every time it sneezed in the cold air.\",\"They crossed a bridge made of old rope that swayed above a rushing river.\"]",
                            Title = "Longer Sentences I"
                        },
                        new
                        {
                            Id = 32,
                            BasePoints = 75,
                            Description = "Building speed with longer text",
                            LevelNumber = 32,
                            Phase = "Drake",
                            PromptTexts = "[\"The forest grew darker as they walked deeper into the ancient woods.\",\"Strange mushrooms glowed with a faint blue light along the narrow trail.\",\"Jimothy held a torch in one hand and kept the dragon close with the other.\",\"Somewhere in the distance, an owl hooted and the dragon hid behind a rock.\"]",
                            Title = "Longer Sentences II"
                        },
                        new
                        {
                            Id = 33,
                            BasePoints = 75,
                            Description = "Typing with flow and rhythm",
                            LevelNumber = 33,
                            Phase = "Drake",
                            PromptTexts = "[\"By noon they found a clearing with a stream and stopped to rest and eat.\",\"The dragon caught a fish by accident when it fell into the shallow water.\",\"Jimothy laughed so hard that he dropped his sandwich into the mud below.\",\"After lunch they dried off in the sun and continued on their long journey.\"]",
                            Title = "Longer Sentences III"
                        },
                        new
                        {
                            Id = 34,
                            BasePoints = 75,
                            Description = "Sentences with question marks and dialogue",
                            LevelNumber = 34,
                            Phase = "Drake",
                            PromptTexts = "[\"\\u0022Where are we going?\\u0022 the dragon seemed to ask with its big round eyes.\",\"Jimothy looked at the map and said, \\u0022We should reach the village by sunset.\\u0022\",\"\\u0022Do you think they will be afraid of you?\\u0022 he asked the little dragon.\",\"The dragon tilted its head as if to say, \\u0022Who could be scared of me?\\u0022\"]",
                            Title = "Questions and Answers"
                        },
                        new
                        {
                            Id = 35,
                            BasePoints = 75,
                            Description = "Stories about the world of dragons",
                            LevelNumber = 35,
                            Phase = "Drake",
                            PromptTexts = "[\"Long ago, dragons filled the skies and their roars echoed across every land.\",\"They came in every color, from deep ocean blue to bright sunrise gold.\",\"The fire dragons lived near volcanoes and could melt stone with a single breath.\",\"Ice dragons preferred the frozen north where snowflakes danced around their wings.\"]",
                            Title = "Dragon Lore I"
                        },
                        new
                        {
                            Id = 36,
                            BasePoints = 75,
                            Description = "The history of dragon riders",
                            LevelNumber = 36,
                            Phase = "Drake",
                            PromptTexts = "[\"In the old days, brave heroes would earn a dragon\\u0027s trust through acts of kindness.\",\"A dragon never forgets someone who helped it, even if many years have passed.\",\"The bond between a rider and dragon was said to be stronger than steel.\",\"Together they could fly faster than the wind and see beyond the horizon.\"]",
                            Title = "Dragon Lore II"
                        },
                        new
                        {
                            Id = 37,
                            BasePoints = 75,
                            Description = "Sentences with numbers mixed in naturally",
                            LevelNumber = 37,
                            Phase = "Drake",
                            PromptTexts = "[\"The castle had 7 towers, each one taller than the last, reaching 200 feet high.\",\"Jimothy counted 14 stars in the sky before the clouds rolled in at midnight.\",\"The dragon ate 3 fish, 2 apples, and about 50 berries for its evening meal.\",\"It took them 5 days to cross the mountain pass and reach the valley below.\"]",
                            Title = "Numbers in Context"
                        },
                        new
                        {
                            Id = 38,
                            BasePoints = 75,
                            Description = "Fast-paced adventure sentences",
                            LevelNumber = 38,
                            Phase = "Drake",
                            PromptTexts = "[\"The ground shook! A massive boulder rolled down the hill straight toward them!\",\"Jimothy grabbed the dragon and dove behind a fallen tree just in time.\",\"The boulder crashed past, taking out three trees and splashing into the lake.\",\"They looked at each other, breathing hard, and then burst out laughing.\"]",
                            Title = "Exciting Action"
                        },
                        new
                        {
                            Id = 39,
                            BasePoints = 75,
                            Description = "Detailed descriptive sentences",
                            LevelNumber = 39,
                            Phase = "Drake",
                            PromptTexts = "[\"The village had small stone houses with red roofs and gardens full of flowers.\",\"A warm golden light spilled from every window into the cool evening air.\",\"The smell of fresh bread and roasting meat drifted down the cobblestone street.\",\"Children played near the fountain while their parents chatted on wooden benches.\"]",
                            Title = "Descriptions"
                        },
                        new
                        {
                            Id = 40,
                            BasePoints = 75,
                            Description = "Longer sentences with commas and clauses",
                            LevelNumber = 40,
                            Phase = "Drake",
                            PromptTexts = "[\"Although the path was steep and the rain made it slippery, they kept climbing.\",\"The dragon, who had grown a little bigger each day, could now glide short distances.\",\"Jimothy knew that if they could reach the top, the view would be worth every step.\",\"When they finally arrived, the sunset painted the whole sky in orange and purple.\"]",
                            Title = "Complex Sentences"
                        },
                        new
                        {
                            Id = 41,
                            BasePoints = 100,
                            Description = "Multiple sentences in a row",
                            LevelNumber = 41,
                            Phase = "Drake",
                            PromptTexts = "[\"The dragon woke up early. It stretched its wings and yawned, sending a tiny puff of smoke into the morning air. Jimothy was still asleep by the campfire.\",\"A rabbit hopped past the campsite. The dragon watched it carefully, its tail twitching back and forth. Then it pounced and missed completely.\"]",
                            Title = "Short Paragraphs I"
                        },
                        new
                        {
                            Id = 42,
                            BasePoints = 100,
                            Description = "Building endurance with longer text",
                            LevelNumber = 42,
                            Phase = "Drake",
                            PromptTexts = "[\"They reached the top of the hill and looked down at the valley below. A river wound through green fields like a silver ribbon. Tiny houses dotted the landscape.\",\"The dragon made a happy sound and flapped its wings. It wanted to fly down, but it was still too small. Jimothy scratched its head and said maybe next week.\"]",
                            Title = "Short Paragraphs II"
                        },
                        new
                        {
                            Id = 43,
                            BasePoints = 100,
                            Description = "Telling stories through typing",
                            LevelNumber = 43,
                            Phase = "Drake",
                            PromptTexts = "[\"The old blacksmith looked at the dragon and smiled. He had not seen one in forty years. He told them that dragons used to visit his shop to have their scales polished.\",\"Jimothy asked if the blacksmith could make a small collar for the dragon. The old man nodded and got to work. By sunset, the dragon wore a tiny golden tag that read: Friend.\"]",
                            Title = "Short Paragraphs III"
                        },
                        new
                        {
                            Id = 44,
                            BasePoints = 100,
                            Description = "Legends of the ancient dragons",
                            LevelNumber = 44,
                            Phase = "Drake",
                            PromptTexts = "[\"The Elder Dragons were the first creatures to walk the earth. They shaped mountains with their claws and filled oceans with their tears of joy. Every river began as a dragon\\u0027s gift.\",\"When an Elder Dragon passed away, a new star would appear in the night sky. The dragons believed that their ancestors watched over them from above, guiding them with gentle starlight.\"]",
                            Title = "Dragon Lore III"
                        },
                        new
                        {
                            Id = 45,
                            BasePoints = 100,
                            Description = "Jimothy and the dragon press on",
                            LevelNumber = 45,
                            Phase = "Drake",
                            PromptTexts = "[\"The map showed a shortcut through the Whispering Caves. Jimothy was nervous, but the dragon marched right in. Its scales began to glow softly, lighting the way through the darkness.\",\"Strange crystals hung from the ceiling like frozen raindrops. The dragon touched one with its nose and it chimed like a tiny bell. Soon the whole cave was singing.\"]",
                            Title = "Adventures Continue"
                        },
                        new
                        {
                            Id = 46,
                            BasePoints = 100,
                            Description = "Descriptive paragraphs about nature",
                            LevelNumber = 46,
                            Phase = "Drake",
                            PromptTexts = "[\"Autumn had arrived and the leaves were turning brilliant shades of red and gold. The air was crisp and cool, perfect for hiking. The dragon loved crunching through the fallen leaves.\",\"Winter brought snow to the mountains. Jimothy built a shelter while the dragon tried to breathe fire for the first time. All it managed was a warm puff, but it was enough to melt some snow for water.\"]",
                            Title = "Weather and Seasons"
                        },
                        new
                        {
                            Id = 47,
                            BasePoints = 100,
                            Description = "Dialogue-heavy paragraphs",
                            LevelNumber = 47,
                            Phase = "Drake",
                            PromptTexts = "[\"A girl named Elara spotted them from her farm. \\u0022Is that a real dragon?\\u0022 she gasped. Jimothy nodded. \\u0022Don\\u0027t worry, it\\u0027s friendly.\\u0022 The dragon proved it by gently nuzzling her hand.\",\"Elara invited them inside for soup. While they ate, she told them about the old dragon tower north of the village. \\u0022Nobody goes there anymore,\\u0022 she said, \\u0022but I hear it glows at night.\\u0022\"]",
                            Title = "Meeting New Friends"
                        },
                        new
                        {
                            Id = 48,
                            BasePoints = 100,
                            Description = "An exciting discovery",
                            LevelNumber = 48,
                            Phase = "Drake",
                            PromptTexts = "[\"The tower stood alone on a rocky hill, covered in vines and moss. As they got closer, the dragon became excited, pulling on Jimothy\\u0027s sleeve. Something about this place felt familiar to it.\",\"Inside, the walls were carved with images of dragons in flight. A spiral staircase led up into the darkness. The dragon began to climb, and Jimothy followed, his torch casting long shadows.\"]",
                            Title = "The Dragon Tower"
                        },
                        new
                        {
                            Id = 49,
                            BasePoints = 100,
                            Description = "Discovering dragon history",
                            LevelNumber = 49,
                            Phase = "Beyond",
                            PromptTexts = "[\"At the top of the tower, they found a room filled with dragon eggs, all dark and cold. The dragon touched them gently, but none responded. These eggs had been sleeping for a very long time.\",\"A stone tablet on the wall told the story of the last dragons. They had hidden their eggs here to keep them safe, hoping that one day someone kind would find them and bring them home.\"]",
                            Title = "Ancient Secrets"
                        },
                        new
                        {
                            Id = 50,
                            BasePoints = 100,
                            Description = "The final stretch of the adventure",
                            LevelNumber = 50,
                            Phase = "Beyond",
                            PromptTexts = "[\"Jimothy carefully packed the sleeping eggs into his bag. The dragon watched proudly, knowing that its family might one day wake up too. Together, they began the long walk home.\",\"As they walked, the dragon flew alongside Jimothy for the first time, strong enough at last to stay in the air. The sun set behind them, painting the sky in every color imaginable.\"]",
                            Title = "The Journey Home"
                        });
                });

            modelBuilder.Entity("DragonForge.Api.Models.Entities.Parent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("DragonForge.Api.Models.Entities.ChildOtp", b =>
                {
                    b.HasOne("DragonForge.Api.Models.Entities.ChildProfile", "ChildProfile")
                        .WithMany()
                        .HasForeignKey("ChildProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChildProfile");
                });

            modelBuilder.Entity("DragonForge.Api.Models.Entities.ChildProfile", b =>
                {
                    b.HasOne("DragonForge.Api.Models.Entities.Parent", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("DragonForge.Api.Models.Entities.DeviceSession", b =>
                {
                    b.HasOne("DragonForge.Api.Models.Entities.ChildProfile", "ChildProfile")
                        .WithMany("DeviceSessions")
                        .HasForeignKey("ChildProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChildProfile");
                });

            modelBuilder.Entity("DragonForge.Api.Models.Entities.LevelAttempt", b =>
                {
                    b.HasOne("DragonForge.Api.Models.Entities.ChildProfile", "ChildProfile")
                        .WithMany("Attempts")
                        .HasForeignKey("ChildProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DragonForge.Api.Models.Entities.LevelDefinition", "LevelDefinition")
                        .WithMany()
                        .HasForeignKey("LevelDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChildProfile");

                    b.Navigation("LevelDefinition");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("DragonForge.Api.Models.Entities.Parent", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("DragonForge.Api.Models.Entities.Parent", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DragonForge.Api.Models.Entities.Parent", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("DragonForge.Api.Models.Entities.Parent", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DragonForge.Api.Models.Entities.ChildProfile", b =>
                {
                    b.Navigation("Attempts");

                    b.Navigation("DeviceSessions");
                });

            modelBuilder.Entity("DragonForge.Api.Models.Entities.Parent", b =>
                {
                    b.Navigation("Children");
                });
#pragma warning restore 612, 618
        }
    }
}
