// <auto-generated />
using DragonForge.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DragonForge.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260409224936_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DragonForge.Api.Models.Entities.LevelDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BasePoints")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("LevelNumber")
                        .HasColumnType("integer");

                    b.Property<int?>("MinWpmForBonus")
                        .HasColumnType("integer");

                    b.Property<string>("Phase")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PromptTexts")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LevelNumber")
                        .IsUnique();

                    b.ToTable("LevelDefinitions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BasePoints = 10,
                            Description = "Practice the left home row keys: a s d f",
                            LevelNumber = 1,
                            Phase = "Egg",
                            PromptTexts = "[\"ff dd ss aa fd sa df as\",\"sad fad dad add ads aff\",\"as sad dad fad dads adds\",\"fads dass sadf fdsa asdf\"]",
                            Title = "Home Row Left Hand"
                        },
                        new
                        {
                            Id = 2,
                            BasePoints = 10,
                            Description = "Practice the right home row keys: j k l ;",
                            LevelNumber = 2,
                            Phase = "Egg",
                            PromptTexts = "[\"jj kk ll ;; jk lk jl kj\",\"jkl lkj kjl ljk ;lk j;l\",\"jk kl l; ;l lk kj j; ;j\",\"jkl; ;lkj kj;l l;kj jkl;\"]",
                            Title = "Home Row Right Hand"
                        },
                        new
                        {
                            Id = 3,
                            BasePoints = 10,
                            Description = "Combine left and right home row: a s d f j k l ;",
                            LevelNumber = 3,
                            Phase = "Egg",
                            PromptTexts = "[\"ask all fall lads flask salad\",\"dad jak lad ask sad fall\",\"fallsasks salads flasks lads\",\"a sad lad asks dad for salad\"]",
                            Title = "Home Row Full"
                        },
                        new
                        {
                            Id = 4,
                            BasePoints = 10,
                            Description = "All home row keys including g and h",
                            LevelNumber = 4,
                            Phase = "Egg",
                            PromptTexts = "[\"gash hash glad flag shag half\",\"flash flags gash halls shall glass\",\"had has gal lag hag jag sag dag\",\"a glad gal shall dash half a flag\"]",
                            Title = "Home Row Complete"
                        },
                        new
                        {
                            Id = 5,
                            BasePoints = 10,
                            Description = "Learn the top row left hand: q w e r t",
                            LevelNumber = 5,
                            Phase = "Egg",
                            PromptTexts = "[\"we wetrew tree were quest\",\"tree wetrew west were qwert\",\"we were free tree wet quest\",\"the tree grew wet where we rest\"]",
                            Title = "Top Row Left"
                        },
                        new
                        {
                            Id = 6,
                            BasePoints = 10,
                            Description = "Learn the top row right hand: y u i o p",
                            LevelNumber = 6,
                            Phase = "Egg",
                            PromptTexts = "[\"you your yip poi you yup\",\"pop pip you your yup poi\",\"you pour your iou yip poi\",\"you pour up yup pop poiopy\"]",
                            Title = "Top Row Right"
                        },
                        new
                        {
                            Id = 7,
                            BasePoints = 10,
                            Description = "Full top row: q w e r t y u i o p",
                            LevelNumber = 7,
                            Phase = "Egg",
                            PromptTexts = "[\"typewriter your power quite wire poetry\",\"write your quote type power rope\",\"quiet poetry typewriter proper routine\",\"you write poetry with power quite proper\"]",
                            Title = "Top Row Full"
                        },
                        new
                        {
                            Id = 8,
                            BasePoints = 15,
                            Description = "Mix home row and top row keys together",
                            LevelNumber = 8,
                            Phase = "Egg",
                            PromptTexts = "[\"the quick red fish just helped sort\",\"quest for gold right where they left\",\"quite right she sold the purple silk\",\"after the quiet hike up the top ridge\"]",
                            Title = "Home + Top Mixed"
                        },
                        new
                        {
                            Id = 9,
                            BasePoints = 10,
                            Description = "Learn the bottom row left hand: z x c v b",
                            LevelNumber = 9,
                            Phase = "Egg",
                            PromptTexts = "[\"box cab vex czar vc bx zap\",\"excavate brace cave vex box cab\",\"brave cave cab box vex czar\",\"the brave cub excavated a cave by a box\"]",
                            Title = "Bottom Row Left"
                        },
                        new
                        {
                            Id = 10,
                            BasePoints = 10,
                            Description = "Learn the bottom row right hand: n m , . /",
                            LevelNumber = 10,
                            Phase = "Egg",
                            PromptTexts = "[\"man men mine moon nom mn\",\"moon name mine noon moan man\",\"name, moon. man, mine. noon, moan.\",\"the man and moon met at noon, no name.\"]",
                            Title = "Bottom Row Right"
                        },
                        new
                        {
                            Id = 11,
                            BasePoints = 10,
                            Description = "Full bottom row: z x c v b n m , . /",
                            LevelNumber = 11,
                            Phase = "Egg",
                            PromptTexts = "[\"combine, vex. ban, mix. zone, comb.\",\"machine verb combine zone mix ban\",\"the brave zombie came back, no venom.\",\"combine zinc and nix, mix boxen, ban.\"]",
                            Title = "Bottom Row Full"
                        },
                        new
                        {
                            Id = 12,
                            BasePoints = 15,
                            Description = "Random letters from all three rows",
                            LevelNumber = 12,
                            Phase = "Egg",
                            PromptTexts = "[\"the quick brown fox jumps over a lazy dog\",\"pack my box with five dozen liquor jugs\",\"crazy viking joked with bad fluxempo\",\"how quickly jumping zebras vex fond dogs\"]",
                            Title = "All Rows Mixed"
                        },
                        new
                        {
                            Id = 13,
                            BasePoints = 15,
                            Description = "Introducing the shift key for capital letters",
                            LevelNumber = 13,
                            Phase = "Egg",
                            PromptTexts = "[\"The Dog Sat Down And Ate His Food\",\"Jack And Jill Went Up The Hill Fast\",\"Sam Ran Quick But Zoe Was Even Faster\",\"My Friend Alex Lives Near Big Park Zoo\"]",
                            Title = "Capital Letters"
                        },
                        new
                        {
                            Id = 14,
                            BasePoints = 15,
                            Description = "Practice the number keys: 1 2 3 4 5 6 7 8 9 0",
                            LevelNumber = 14,
                            Phase = "Egg",
                            PromptTexts = "[\"12345 67890 13579 24680\",\"I have 3 cats and 2 dogs at home\",\"Room 42 has 7 desks and 10 chairs\",\"She scored 95 out of 100 on test 4\"]",
                            Title = "Numbers Row"
                        },
                        new
                        {
                            Id = 15,
                            BasePoints = 15,
                            Description = "Practice common punctuation: . , ! ? ' \"",
                            LevelNumber = 15,
                            Phase = "Egg",
                            PromptTexts = "[\"Hello, world! How are you? I\\u0027m fine.\",\"\\u0022Wow!\\u0022 she said. \\u0022That\\u0027s amazing, right?\\u0022\",\"Wait, what? No way! That\\u0027s so cool.\",\"He asked, \\u0022Can you help?\\u0022 I said, \\u0022Yes!\\u0022\"]",
                            Title = "Common Punctuation"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
